#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
测试入口
"""

import os
import sys
import subprocess
import logging

import pytest

from config import config as Config

logging.basicConfig(level=logging.INFO,
                    format='[%(levelname)s %(asctime)s %(filename)s %(funcName)s line:%(lineno)d]: %(message)s',
                    datefmt='%y%m%d %H:%M:%S')

if __name__=='__main__':
    testcase = sys.argv[1]
    logging.info(testcase)
    xml_report_path = os.path.join(Config.REPORT, 'xml')
    html_report_path = os.path.join(Config.REPORT, 'html')
    pytest.main(['-s', '--alluredir', xml_report_path, testcase])
    cmd = 'allure generate --clean {xml} -o {html}'.format(xml=xml_report_path, html=html_report_path)
    logging.info(cmd)
    subprocess.call(cmd, shell=True)